### ISSUE TITLE
Import parameters from other subsections as well

### ISSUE THREAD

**Issue by artur-gajewski** [Incenteev/ParameterHandler#35]
If the parameters.yml-dist file has following structure:

``` yaml
parameters:
   login_required: false

twig:
    globals:
        show_forkme: true
```

Only the parameters section will be checked for missing parameters and imported, but the other sections remain unchecked / unimported. Should also import these.
