### ISSUE TITLE
Provide some sort of hint or explanation as to what parameters mean

### ISSUE THREAD

**Issue by Intrepidity** [Incenteev/ParameterHandler#69]
It would be nice in my opinion if a parameter in the .dist file is prepended by a comment, that that comment would also be shown when asking for the parameters.

i.e.:
```yml
parameters:
    # A secret key that's used to generate certain security-related tokens
    secret:            test
```

would result in:
```
Some parameters are missing. Please provide them.
A secret key that's used to generate certain security-related tokens: secret (test):
```

It is sometimes hard to convey in a variable name what you want users to input upon install.
