### ISSUE TITLE
Adding support for variable parameters

### ISSUE THREAD

**Issue by sandvige** [Incenteev/ParameterHandler#74]
In Symfony2, it's possible to define this:
``` yaml
framework:
    templating:
        engines: ['twig']
        assets_version: %assets_version%
```

And it could be great to be able to define in the dist file something like that:
``` yaml
parameters:
    assets_version: {{ date().timestamp }}
```

This could be very useful for cache busting on deployment
